"""expandir carta_porte_records

Revision ID: 13ec654438b5
Revises: 0001
Create Date: 2026-09-14 03:46:07.289429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ec654438b5'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_porte_records', sa.Column('emisor_rfc', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('receptor_rfc', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('tipo_cfdi', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_clave', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_calle', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_numero_exterior', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('origen_numero_interior', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('origen_colonia', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_localidad', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('origen_municipio', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_estado', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_pais', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_codigo_postal', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('origen_fecha_hora_salida', sa.DateTime(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_clave', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_calle', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_numero_exterior', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('destino_numero_interior', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('destino_colonia', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_localidad', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('destino_municipio', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_estado', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_pais', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_codigo_postal', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('destino_fecha_hora_llegada', sa.DateTime(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('distancia_recorrida_km', sa.Float(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('mercancia_clave_prod_serv', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('mercancia_peso_bruto_kg', sa.Float(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('mercancia_peso_neto_kg', sa.Float(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('mercancia_clave_unidad', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('material_peligroso', sa.Boolean(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('mercancia_embalaje', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('tipo_transporte', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('config_vehicular', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('placa_camion', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('placa_remolque', sa.String(), nullable=True))
    op.add_column('carta_porte_records', sa.Column('numero_permiso_sict', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('aseguradora_nombre', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('poliza_numero', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('operador_nombre', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('operador_rfc', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('operador_licencia', sa.String(), nullable=False))
    op.add_column('carta_porte_records', sa.Column('operador_domicilio', sa.String(), nullable=False))
    op.drop_column('carta_porte_records', 'transport_config')
    op.drop_column('carta_porte_records', 'weight_kg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_porte_records', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('carta_porte_records', sa.Column('transport_config', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carta_porte_records', 'operador_domicilio')
    op.drop_column('carta_porte_records', 'operador_licencia')
    op.drop_column('carta_porte_records', 'operador_rfc')
    op.drop_column('carta_porte_records', 'operador_nombre')
    op.drop_column('carta_porte_records', 'poliza_numero')
    op.drop_column('carta_porte_records', 'aseguradora_nombre')
    op.drop_column('carta_porte_records', 'numero_permiso_sict')
    op.drop_column('carta_porte_records', 'placa_remolque')
    op.drop_column('carta_porte_records', 'placa_camion')
    op.drop_column('carta_porte_records', 'config_vehicular')
    op.drop_column('carta_porte_records', 'tipo_transporte')
    op.drop_column('carta_porte_records', 'mercancia_embalaje')
    op.drop_column('carta_porte_records', 'material_peligroso')
    op.drop_column('carta_porte_records', 'mercancia_clave_unidad')
    op.drop_column('carta_porte_records', 'mercancia_peso_neto_kg')
    op.drop_column('carta_porte_records', 'mercancia_peso_bruto_kg')
    op.drop_column('carta_porte_records', 'mercancia_clave_prod_serv')
    op.drop_column('carta_porte_records', 'distancia_recorrida_km')
    op.drop_column('carta_porte_records', 'destino_fecha_hora_llegada')
    op.drop_column('carta_porte_records', 'destino_codigo_postal')
    op.drop_column('carta_porte_records', 'destino_pais')
    op.drop_column('carta_porte_records', 'destino_estado')
    op.drop_column('carta_porte_records', 'destino_municipio')
    op.drop_column('carta_porte_records', 'destino_localidad')
    op.drop_column('carta_porte_records', 'destino_colonia')
    op.drop_column('carta_porte_records', 'destino_numero_interior')
    op.drop_column('carta_porte_records', 'destino_numero_exterior')
    op.drop_column('carta_porte_records', 'destino_calle')
    op.drop_column('carta_porte_records', 'destino_clave')
    op.drop_column('carta_porte_records', 'origen_fecha_hora_salida')
    op.drop_column('carta_porte_records', 'origen_codigo_postal')
    op.drop_column('carta_porte_records', 'origen_pais')
    op.drop_column('carta_porte_records', 'origen_estado')
    op.drop_column('carta_porte_records', 'origen_municipio')
    op.drop_column('carta_porte_records', 'origen_localidad')
    op.drop_column('carta_porte_records', 'origen_colonia')
    op.drop_column('carta_porte_records', 'origen_numero_interior')
    op.drop_column('carta_porte_records', 'origen_numero_exterior')
    op.drop_column('carta_porte_records', 'origen_calle')
    op.drop_column('carta_porte_records', 'origen_clave')
    op.drop_column('carta_porte_records', 'tipo_cfdi')
    op.drop_column('carta_porte_records', 'receptor_rfc')
    op.drop_column('carta_porte_records', 'emisor_rfc')
    # ### end Alembic commands ###
